image: kirinnee/go-with-docker:latest

stages:
  - build
  - deploy

Build:
  stage: build
  script:
    - mkdir build
    - env GOOS=windows GOARCH=amd64 go build -o /builds/atomi-cloud/anode/build/anode.exe
    - env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -a -installsuffix cgo -o /builds/atomi-cloud/anode/build/anode
    - env GOOS=darwin GOARCH=amd64 go build -o /builds/atomi-cloud/anode/build/anode-mac
  artifacts:
    paths:
      - ./build/
    expire_in: 90 days

Deploy:
  stage: deploy
  script:
    - echo "Hi"